---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled


jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variable if valid label
        id: pr_set_variable
        run: |
          echo "hasValidLabels=true" >> "$GITHUB_ENV"
          echo "valid labels"
        if: |
          (
            ${{ github.event.label.name == 'enhancement' }} ||
            ${{ github.event.label.name == 'deprecated' }} ||
            ${{ github.event.label.name == 'refactoring' }} ||
            ${{ github.event.label.name == 'pr: breaking' }} ||
            ${{ github.event.label.name == 'pr: clean' }} ||
            ${{ github.event.label.name == 'pr: fix' }} ||
            ${{ github.event.label.name == 'pr: new feature' }} ||
            ${{ github.event.label.name == 'pr: test' }}
          )

      - name: Comment if invalid label
        id: pr_comment
        if: (!${{ steps.pr_set_variable.outputs.hasValidLabels == true }})
        uses: actions/github-script@v4
        with:
          script: |
              // Post a warning comment
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: ':warning: :warning: :warning:<br>@'+context.repo.owner+' your PR does not include any descriptive label :label:<br> Make sure to add an appropriate [PR label](https://github.com/sofa-framework/sofa/labels) before merge.<br>:warning: :warning: :warning:'
              });
              exit 1
          github-token: ${{ secrets.GITHUB_TOKEN }}
