---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled


jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get PR labels
        id: pr_get_labels
        run: |
          echo "labels=${{ context.issue.labels }}" >> "$GITHUB_ENV"
          echo "$labels"

      - name: Set environment variable if valid label
        uses: actions/github-script@v4
        id: pr_set_variable
        run: |
          echo "hasValidLabels=true" >> "$GITHUB_ENV"
          echo "valid labels"
        if: |
          (contains(steps.pr_get_labels.outputs.labels, 'enhancement') ||
           contains(steps.pr_get_labels.outputs.labels, 'deprecated') ||
           contains(steps.pr_get_labels.outputs.labels, 'refactoring') ||
           contains(steps.pr_get_labels.outputs.labels, 'pr: clean') ||
           contains(steps.pr_get_labels.outputs.labels, 'pr: breaking') ||
           contains(steps.pr_get_labels.outputs.labels, 'pr: new feature') ||
           contains(steps.pr_get_labels.outputs.labels, 'pr: fix') ||
           contains(steps.pr_get_labels.outputs.labels, 'pr: test')
          )

      - name: Comment if invalid label
        id: pr_comment
        if: (!${{ steps.pr_set_variable.outputs.hasValidLabels == true }})
        uses: actions/github-script@v4
        with:
          script: |
              // Post a warning comment
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: ':warning: :warning: :warning:<br>@'+context.repo.owner+' your PR does not include any descriptive label :label:<br> Make sure to add an appropriate [PR label](https://github.com/sofa-framework/sofa/labels) before merge.<br>:warning: :warning: :warning:'
              });
          github-token: ${{ secrets.GITHUB_TOKEN }}