---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled


jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels and Add Comment
        id: check_labels_and_comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const labels = context.payload.pull_request.labels.map(label => label.name);

            if (!labels.includes('enhancement') && !labels.includes('duplicate')) {
              const comment = 'foo';
              const octokit = context.github;
              await octokit.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
              core.setFailed('Invalid PR label')
            }

            console.log('Labels:', labels.join(', '));
