---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled


jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Comment if missing descriptive labels
        id: pr_labels
        uses: actions/github-script@v4
        if: ! contains(steps.pr_labels.outputs.labels, 'enhancement')
        - run: |
          env | grep GITHUB_PR_LABEL || true
        with:
          script: |
              // Post a warning comment
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: ':warning: :warning: :warning:<br>@'+context.repo.owner+' your PR does not include any descriptive label :label:<br> Make sure to add an appropriate [PR label](https://github.com/sofa-framework/sofa/labels) before merge.<br>:warning: :warning: :warning:'
              });
          github-token: ${{ secrets.GITHUB_TOKEN }}