---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    
jobs:

  check_labels:
    name: Check for Test Plan Approved label
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        uses: actions/github-script@v4
        with:
          script: |
            echo context.issue.labels
            // Post a warning comment
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning: @'+context.repo.owner+': your PR does not include any descriptive label :warning:'
            });
          repo-token: ${{ secrets.GITHUB_TOKEN }}