---
name: Label Checker
on:
  pull_request:
    branches: [release]
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    
jobs:

  check_labels:
    name: Check for Test Plan Approved label
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          # Needs to have a Test Plan Approved label if not part of any of the pods below
          any_of: enhancement,refactoring


      - name: Comment
        uses: actions/github-script@v4
        with:
          script: |
            // Post a warning comment
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning: @'+context.repo.owner+': your PR does not include any descriptive label :warning:'
            });