---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    
jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
      - run: |
          if [ -n "enhancement" ]; then
            echo "POUET POUET"
          fi

      - name: Comment
        uses: actions/github-script@v4
        with:
          script: |
            // Post a warning comment
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':x: @'+context.repo.owner+' your PR does not include any descriptive label :x:<br>:warning: :warning: :warning:<br> Make sure to add an appropriate [PR label](https://github.com/sofa-framework/sofa/labels) before merge.'
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}