name: Post - GitHub stats for activity tracking

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,15 * *"   # Every 1st & 15th of the month

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install python-graphql-client
          pip install python-dateutil
          pip install requests
          pip install beautifulsoup4

        working-directory: ${{ github.workspace }}

      - name: Get download stats
        run: |
          python scripts/github_activity/get_downloads.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_GITHUB_STATS_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get cloner stats
        run: |
          python scripts/github_activity/get_cloners.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_GITHUB_STATS_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get GitHub stats - PR issues discussions
        run: |
          python scripts/github_activity/get_repo_stats.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_GITHUB_STATS_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
