name: Post GitHub Discussions Statistics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1' # Every Monday at 7:00 AM UTC (9:00 AM CET)
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Use the desired Python version

      - name: Install dependencies
        run: |
          pip install python-graphql-client
          pip install python-dateutil
        working-directory: ${{ github.workspace }}

      - name: Run script get-weekly-discussions-stats.py
        id: create_message
        run: |
          python scripts/send-discussions-stats.py
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

